[[tls.certificates]] 
   certFile = “/certs/golemstats.com.crt” 
   keyFile = “/certs/golemstats.com.key”

[[tls.certificates]] 
   certFile = “/certs/api.golemstats.com.crt” 
   keyFile = “/certs/api.golemstats.com.key”