#Location: .github/workflows/custom_config.yml

name: Build and push containers to Dockerhub
env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

on:
  push:
    branches:
      - mono-repo-migration #Use your own branch here (Might be staging or testing)
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Git clone on our repo
        uses: actions/checkout@v2

      - name: Login to Dockerhub
        run: make login

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build AMD64 images
        run: make build-amd64

      - name: Push AMD64 images
        run: make push-amd64

      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            script: |
                docker service update --force --image phillipjensen/golem-stats-backend:${{ github.sha }} golemstats_webserver
                docker service update --force --image phillipjensen/golem-stats-backend-celery:${{ github.sha }} golemstats_celery
                docker service update --force --image phillipjensen/golem-stats-backend-celery-beat:${{ github.sha }} golemstats_celery_beat
  
      - name: Build ARM64 images
        run: make build-amd64